# name: Weather SMS Alert

# on:
#   schedule:
#     # Runs every minute
#     - cron: '* * * * *'

#   # Manual trigger button
#   workflow_dispatch:

# jobs:
#   run-weather-alert:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.12'

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Run weather alert script
#         env:
#           ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
#           AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
#           API_KEY: ${{ secrets.API_KEY }}
#         run: python main.py
